spring:
  profiles:
    active: common    #   *** 根据项目配置,极个别特殊项目才需配置,正常情况: common ***
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    #    url: jdbc:mysql://127.0.0.1:3306/dsl?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    url: jdbc:mysql://127.0.0.1:3306/dsl?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8


# WMS 任务生产方式, 通讯地址配置
server:
  # dss、oes、mk、std  系统版本, 必须配置
  #  version: dss
  #  对应具体定制化项目, 与系统版本一致则默认无定制化需求
  #  project: dss
  # tcp、 http、 db(直接插数据库)  通讯方式/任务生成方式, 必须配置
  #  type: tcp
  #  connType: tcp
  WMS:
    port: 9999
    end: "#"
  mfc:
    IP: 10.2.2.84
    port: 9392
    end: "*"
  device:
    ip: 10.2.2.84

# 任务生成策略
strategy:
  inbound:
    machine: boxLift     # 入库提升机选择 【boxLift: 仅料箱提升机入库;】 【lift: 仅换层提升机入库;】 【boxLift、lift: 双入库】
    isAppoint: true         # 是否指定入库货位
    intervalTime: 3000     # 任务间隔时间单位：秒
    async: true         # 异步指定入库 正泰，香港bps
    exitArea: false           # false:没分区  true:有分区
    everyLevelNums: 1     #针对的是单个提升机, 而不是库内当前层, ==>>单个提升机每层最多送多少箱子
  outbound:
    intervalTime: 10000
    everyLevelNums: 9    # 当每层任务数设置为与巷道数相等的条件下，当前层每个巷道生成一条任务
    ignoreExitTask: false     # N：当前层有任务则不生成任务，当任务数小于等于2时，开始生成任务； Y：持续不间断的生成任务；但任务积压上限100
  move:
    intervalTime: 10000
    everyLevelNums: 9
    ignoreExitTask: false
    exitArea: false           # false:没分区  true:有分区

mybatis:
  mapper-locations=classpath:mapper/*/*.xml:

project:
  name: ${spring.profiles.active}


